files:
  - source: /Library/en.lproj/*.strings
    translation: /Library/%two_letters_code%.lproj/%original_file_name%
  - source: /Zap/en.lproj/*.strings
    translation: /Zap/%two_letters_code%.lproj/%original_file_name%
