disabled_rules:
  - trailing_whitespace
  - line_length
  - nesting
opt_in_rules:
  - no_fallthrough_only
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - modifier_order
  - empty_xctest_method
  - convenience_type
  - conditional_returns_on_newline
excluded:
  - Pods
  - SwiftLnd/Api/Generated
  - Library/Generated
  - vendor
identifier_name:
  excluded:
    - id
    - t
conditional_returns_on_newline:
  if_only: true

custom_rules:
  callback_naming:
    name: "Callback naming"
    regex: "callback:"
    message: Prefer 'completion' over 'callback'"
    severity: warning
  localized_string:
    name: "Avoid NSLocalizedString"
    regex: "NSLocalizedString"
    message: "Use .localized instead"
    severity: error
  cast_to_localized_error:
    name: "Cast to LocalizedError"
    regex: "as\\? LocalizedError"
    message: "don't cast to LocalizedError. Use .localizedDescription"
    severity: error
  localizable_error:
    name: Localizable Error"
    regex: "Error.*:.*Localizable"
    message: "Errors should be LocalizedError"
    severity: error
