branches:
  except:
    - localization
osx_image: xcode10.2
language: objective-c
xcode_workspace: Zap.xcworkspace
xcode_scheme: Zap
cache: bundler
git:
  quiet: true
  depth: 3
notifications:
  email:
    on_success: never
    on_failure: change
script:
  - bundle exec fastlane tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Library' -J 'Lightning'
