# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

default_platform(:ios)

desc "Update build number."
lane :build_number do
  new_build_number = Time.now.strftime("%Y.%m.%d.%H.%M")
  increment_build_number(build_number: new_build_number)
end

desc "Update app version."
lane :change_version do |options|
  if version = options[:version] 
    increment_version_number(version_number: version)
  else 
    version = prompt(text: "Please enter the version number: ")
  end
  increment_version_number(version_number: version)
end

desc "Builds new Beta Build and uploads it to S3."
lane :beta do
  unless ENV.key?('ZAP_BETA_S3_ACCESS_KEY')
    UI.user_error!("ZAP_BETA_S3_ACCESS_KEY not set.")
  end

  ensure_git_status_clean
  build_number
  build_ios_app(
    workspace: "Zap.xcworkspace",
    configuration: "Debug",
    scheme: "Zap",
    output_directory: "./builds/beta",
    export_method: "ad-hoc",
    export_options: {
      provisioningProfiles: { 
        "com.jackmallers.zap" => "zap ad-hoc Distribution",
        "com.jackmallers.zap.ZapMessages" => "zapMessages ad-hoc Distribution"
      }
    }
  )  
  aws_s3(
    access_key: ENV['ZAP_BETA_S3_ACCESS_KEY'],
    secret_access_key: ENV['ZAP_BETA_S3_SECRET_ACCESS_KEY'],
    bucket: ENV['ZAP_BETA_S3_BUCKET'],
    region: ENV['ZAP_BETA_S3_REGION'],
    ipa: './builds/beta/Zap.ipa',
    app_directory: 'ios-beta',
    upload_metadata: true
  )
  sh("git reset --hard")

  slack(
    message: "Just uploaded a new iOS beta: " + ENV['ZAP_BETA_S3_URL'],
    use_webhook_configured_username_and_icon: true,
    default_payloads: []
  )
end

desc "Add a new UDID to developer portal and update adhoc provisioning profile."
lane :udid do
  device_name = prompt(text: "Device name: ")
  udid = prompt(text: "UDID: ")
  
  register_device(
    name: device_name,
    udid: udid
  )

  get_provisioning_profile(
    adhoc: true,
    force: true,
    app_identifier: "com.jackmallers.zap",
    provisioning_name: "zap ad-hoc Distribution"
  )

  get_provisioning_profile(
    adhoc: true,
    force: true,
    app_identifier: "com.jackmallers.zap.ZapMessages",
    provisioning_name: "zapMessages ad-hoc Distribution"
  )
end

desc "Generate new app icon assets."
lane :update_app_icon do
  appicon(
    appicon_image_file: 'logo.png',
    appicon_path: 'Zap/Assets.xcassets',
    appicon_devices: [:iphone, :ios_marketing]
  )
end

desc "Run all tests."
lane :tests do
  run_tests(
    workspace: "Zap.xcworkspace",
    devices: ["iPhone 8"],
    scheme: "Zap"
  )
end
