# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

opt_out_usage
default_platform(:ios)

app_identifier = ["com.jackmallers.zap", "com.jackmallers.zap.Sticker", "com.jackmallers.zap.Widget"]

lane :switch_mainnet do
  ids = {
    "Zap/Info.plist" => "com.jackmallers.zap.mainnet",
    "Sticker/Info.plist" => "com.jackmallers.zap.mainnet.Sticker",
    "Widget/Info.plist" => "com.jackmallers.zap.mainnet.Widget",
  }
  ids.each do |key, value|
    update_app_identifier(
      plist_path: key,
      app_identifier: value
    )
  end

  update_app_icon(image: 'logo_mainnet.png')
end

lane :mainnet do |options|
  pre_upload
  check_release_branch('release/mainnet')
  switch_mainnet

  mainnet_ids = [
    "com.jackmallers.zap.mainnet",
    "com.jackmallers.zap.mainnet.Sticker",
    "com.jackmallers.zap.mainnet.Widget",
  ]

  if options[:build_number]
    build_number = options[:build_number]
  else
    build_number = latest_testflight_build_number(
      app_identifier: "com.jackmallers.zap.mainnet",
      initial_build_number: 0
    ) + 1
  end

  increment_build_number(build_number: build_number)

  sync_code_signing(
    readonly: is_ci,
    username: ENV['MATCH_USER'],
    app_identifier: mainnet_ids,
    type: "appstore"
  )

  build_ios_app(
    workspace: "Zap.xcworkspace",
    scheme: "Zap",
    configuration: "Debug",
    output_directory: "./builds/alpha",
    export_method: "app-store"
  )

  upload_to_testflight(
    app_identifier: "com.jackmallers.zap.mainnet",
    username: ENV['ITUNESCONNECT_USER'],
    skip_waiting_for_build_processing: true
  )

  add_git_tag

  reset_git_repo(force: true, disregard_gitignore: false)
end

private_lane :pre_upload do
  ensure_bundle_exec
  sh("(cd .. ; shasum -c .lndmobile.sha1)")
  sh("python3 check_localizable.py")
  if not is_ci?
    ensure_git_status_clean
  end
end

def check_release_branch(prefix)
  branch = git_branch
  branch_parts = branch.split('-')
  if branch_parts.count != 2 || branch_parts[0] != prefix
    UI.user_error!("only release from a release branch (e.g. release/testflight-0.4.0)")
  end 
  increment_version_number(version_number: branch_parts[1])
end

desc "Builds new Alpha Build with local lnd enabled and uploads it to Testflight."
lane :testnet do
  pre_upload
  check_release_branch('release/testflight')

  update_app_icon(image: 'logo_testnet.png')

  increment_build_number(build_number:
    latest_testflight_build_number(
      initial_build_number: 0
    ) + 1
  )

  sync_code_signing(
    readonly: is_ci,
    username: ENV['MATCH_USER'],
    app_identifier: app_identifier,
    type: "appstore"
  )

  build_ios_app(
    workspace: "Zap.xcworkspace",
    scheme: "Zap",
    configuration: "Debug",
    output_directory: "./builds/alpha",
    export_method: "app-store"
  )

  upload_to_testflight(
    username: ENV['ITUNESCONNECT_USER'],
    skip_waiting_for_build_processing: true
  )

  add_git_tag

  slack(
    message: "Just uploaded a new iOS alpha to Testflight",
    use_webhook_configured_username_and_icon: true,
    default_payloads: []
  )

  reset_git_repo(force: true, disregard_gitignore: false)
end

desc "Release"
lane :release do
  pre_upload
  check_release_branch('release/appstore')

  version = get_version_number(
    xcodeproj: "Zap.xcodeproj",
    target: "Zap"
  )

  increment_build_number(build_number:
    app_store_build_number(
      live: false,
      initial_build_number: 0,
      version: version
    ) + 1
  )

  sync_code_signing(
    readonly: is_ci,
    username: ENV['MATCH_USER'],
    app_identifier: app_identifier,
    type: "appstore"
  )

  build_ios_app(
    workspace: "Zap.xcworkspace",
    scheme: "Zap",
    configuration: "Release",
    output_directory: "./builds/appstore",
    export_method: "app-store"
  )

  upload_to_app_store(
    username: ENV['ITUNESCONNECT_USER'],
    skip_metadata: true,
    skip_screenshots: true
  )

  add_git_tag

  slack(
    message: "Just uploaded a new iOS verstion to the app store",
    use_webhook_configured_username_and_icon: true,
    default_payloads: []
  )

  reset_git_repo(force: true, disregard_gitignore: false)
end

desc "Generate new app icon assets."
lane :update_app_icon do |options|
  if option_image = options[:image]
    image = option_image
  else
    image = 'logo.png'
  end
  appicon(
    appicon_image_file: image,
    appicon_path: 'Zap/Assets.xcassets',
    appicon_devices: [:iphone, :ios_marketing]
  )
end

desc "Run all tests."
lane :tests do
  if is_ci?
    carthage(
      command: "bootstrap",
      platform: "iOS",
    )
  end

  swiftlint()
  
  run_tests(
    workspace: "Zap.xcworkspace",
    configuration: "Debug",
    devices: ["iPhone 8"],
    scheme: "Zap",
    slack_only_on_failure: true,
    code_coverage: true
  )
end

lane :screenshots do
  capture_ios_screenshots(
    number_of_retries: 0,
    stop_after_first_error: true
  )
end

lane :upload_screenshots do
  upload_to_app_store(
    username: ENV['ITUNESCONNECT_USER'],
    skip_binary_upload: true,
    skip_metadata: true
  )
end

lane :upload_metadata do
  upload_to_app_store(
    username: ENV['ITUNESCONNECT_USER'],
    skip_binary_upload: true,
    skip_screenshots: true
  )
end

lane :clean do
  reset_git_repo(force: true, disregard_gitignore: false)
end

lane :travis do
  setup_travis

  branch = git_branch
  if branch.start_with?('release/testflight-')
    testnet
  elsif branch.start_with?('release/mainnet-')
    mainnet
  elsif branch.start_with?('release/appstore-')
    release
  else
    tests
  end
end

