# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone XS Max",
  "iPhone X"
])

languages([
  'ca',
  'cs',
  'da',
  'de-DE',
  'el',
  'en-US',
  'es-ES',
  'fi',
  'fr-FR',
  'hr',
  'hu',
  'it',
  'ja',
  'ko',
  'nl-NL',
  'pl',
  'pt-BR',
  'pt-PT',
  'ro',
  'ru',
  'sv',
  'tr',
  'uk',
  'vi'
])

# The name of the scheme which contains the UI Tests
scheme("SnapshotUITests")

