# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone XS Max",
  "iPhone X"
])

languages([
  "en-US",
  "de-DE",
  "it-IT",
  ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme("SnapshotUITests")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

