# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone XS Max",
  "iPhone X"
])

languages(['ca', 'cs', 'da', 'de-DE', 'el', 'en-US', 'es-ES', 'fi', 'fr-FR', 'hr', 'hu', 'it', 'ja', 'ko', 'nl-NL', 'pl', 'pt-BR', 'pt-PT', 'ro', 'ru', 'sv', 'tr', 'uk', 'vi', 'zh-Hans', 'zh-Hant'])

# The name of the scheme which contains the UI Tests
scheme("SnapshotUITests")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

