//
//  Zap
//
//  Created by Otto Suess on 20.05.18.
//  Copyright © 2018 Zap. All rights reserved.
//

import Foundation
import SwiftLnd

/// the qrCode or json generated by zapconnect
struct ZapconnectQRCode: Codable, RemoteRPCConfigurationType {
    let certificate: String
    let macaroon: Data
    let url: URL
    
    enum CodingKeys: String, CodingKey {
        case certificate = "c"
        case macaroon = "m"
        case url = "ip"
    }
    
    init?(json: String) {
        guard
            let data = json.data(using: .utf8),
            let remoteNodeConfiguration = try? JSONDecoder().decode(ZapconnectQRCode.self, from: data)
            else { return nil }
        self = remoteNodeConfiguration
    }
    
    var rpcConfiguration: RemoteRPCConfiguration {
        let certificate = Pem(key: self.certificate).string
        let macaroon = Macaroon(data: self.macaroon)
        
        return RemoteRPCConfiguration(certificate: certificate, macaroon: macaroon, url: url)
    }
}
